services:
  python-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: insight-agent
    restart: always
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - storage:/data
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  storage: